lucas_2.0/Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using lucas_2._0.Models;
using lucas_2._0.Views.Admin;
using Microsoft.AspNetCore.Authorization;

namespace lucas_2._0.Controllers
{
    public class AdminController : Controller
    {
        private readonly ApplicationContext _context;
        private readonly DataService _dataService;
        private readonly AccountService _accountService;

        public AdminController(ApplicationContext context, DataService dataService, AccountService accountService)
        {
            _context = context;
            _dataService = dataService;
            _accountService = accountService;   
        }

        [AllowAnonymous]
        [HttpGet("/Admin/Register")]
       
        public IActionResult Register()
        {
            return View();
        }

        [HttpPost("/Admin/Register")]
        public async Task<IActionResult> RegisterAsync(RegisterVM viewModel)
        {
            if (!ModelState.IsValid)
                return View();

            // Try to register user
            var errorMessage = await _accountService.TryRegisterAsync(viewModel);
            if (errorMessage != null)
            {
                // Show error
                ModelState.AddModelError(string.Empty, errorMessage);
                return View();
            }



            return RedirectToAction(nameof(IndexList));
        }

        [HttpGet("/Admin/Login")]
        public IActionResult Login()
        {
            return View();
        }

        [HttpPost("/Admin/Login")]
        public async Task<IActionResult> LoginAsync(LoginVM viewModel)
        {
            if (!ModelState.IsValid)
                return View();

            // Check if credentials is valid (and set auth cookie)
            var success = await _accountService.TryLoginAsync(viewModel);
            if (!success)
            {
                // Show error
                ModelState.AddModelError(string.Empty, "Login failed");
                return View();
            }

            // Redirect user
            return RedirectToAction(nameof(IndexList));



        }
        [HttpGet]
        public async Task<IActionResult> LogOutAsync()
        {
            await _accountService.SignOutAsync();
            return RedirectToAction("");
        }

        // GET: Admin
        [HttpGet("/Admin")]
        public async Task<IActionResult> IndexList()
        {
              return View(await _dataService.IndexView());
        }

        // GET: Admin/SubCategory/5
        [HttpGet("/admin/subcategory/{id}")]
        public async Task<IActionResult> SubCategory(int id)
        {
                       
            return View(_dataService.GetSubCategories(id));
        }
        //GET Admin/AddOrEditCategory
        [HttpGet("/admin/AddOrEditCategory/{id?}")]
        public IActionResult AddOrEditCategory(int? id)
        {
            if (id == null)
                return View(new AddOrEditCategoryVM());
            else
                return View(_dataService.GetCategory(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEditCategory(AddOrEditCategoryVM model)
        {
            if (ModelState.IsValid)
            {
                if (model.CategoryId == 0)
                    await _dataService.AddCategoryAsync(model);
                else
                    await _dataService.EditCategoryAsync(model);

               
                return RedirectToAction(nameof(IndexList));
            }
            return View(model);
        }

        //GET Admin/AddOrEditSubCategory
        [HttpGet("/admin/addoreditsubcategory/{id?}")]
        public IActionResult AddOrEditSubCategory(int? id, int subCategoryId, string categoryName)
        {
            if (subCategoryId == null)
                return View(new AddOrEditSubCategoryVM() { CategoryId = subCategoryId, CategoryName = categoryName });
            else
                return View(_dataService.GetSubCategory(id, subCategoryId, categoryName));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEditSubCategory(AddOrEditSubCategoryVM model)
        {
            if (ModelState.IsValid)
            {
                if (model.SubCategoryId == 0)
                    await _dataService.AddSubCategoryAsync(model);
                else
                    await _dataService.EditSubCategoryAsync(model);


                return RedirectToAction(nameof(IndexList));
            }
            return RedirectToAction(nameof(IndexList));
        }

        [HttpGet("/admin/addoreditsubcategory/Posts/{subCategoryId}")]
        //[Route("Posts/{subCategoryId}")]
        //GET Admin/Posts
        public IActionResult Posts(int subCategoryId)
        {
            return View(_dataService.GetListOfPosts(subCategoryId));
        }

        //GET Admin/AddOrEditPosts
        [HttpGet("AddOrEditPosts/{subCategoryId}/{id?}")]
        //[Route("AddOrEditPosts/{subCategoryId}/{id?}")]
        public IActionResult AddOrEditPosts(int? id, int subCategoryId)
        {
            if (id == null)
                return View(new AddOrEditPostsVM() { SubCategoryId = subCategoryId});
            else
                return View(_dataService.GetPosts(id));
            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEditPosts(AddOrEditPostsVM model)
        {
            if (ModelState.IsValid)
            {
                if (model.Id == 0)
                    await _dataService.AddPostsAsync(model);
                else
                    await _dataService.EditPostsAsync(model);


                return RedirectToAction(nameof(IndexList));
            }
            return RedirectToAction(nameof(IndexList));
        }

        // GET: Admin/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.Id == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Posts == null)
            {
                return Problem("Entity set 'ApplicationContext.Categories'  is null.");
            }
            var post = await _context.Posts.FindAsync(id);
            if (post != null)
            {
                _context.Posts.Remove(post);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(IndexList));
        }

        private bool CategoryExists(int id)
        {
          return (_context.Categories?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

lucas_2.0/ViewComponents/MenuListViewComponent.cs
using lucas_2._0.Models;
using Microsoft.AspNetCore.Mvc;

namespace lucas_2._0.ViewComponents
{
    public class MenuListViewComponent : ViewComponent
    {
        List<MenuList> MenuItems = new List<MenuList>();
        private readonly MenuList _menuList;

        public MenuListViewComponent(MenuList menuList)
        {
            _menuList = menuList;
            MenuItems = _menuList.MenuListItems();
        }


        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = MenuItems;
            return await Task.FromResult((IViewComponentResult)View("MenuList", model));
        }
    }
}

lucas_2.0/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Code Cave</title>


    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
    <script src="https://cdn.tiny.cloud/1/xz2iauvbk2f6ouxs8c2buqbbvb2rw4ben7j7m0cckkq4n2i8/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600&display=swap" rel="stylesheet">
    <link href="~/css/site.css" rel="stylesheet" />
    <script src="~/js/prism.js"></script>
    <script src="~/js/prism-darkmode.js"></script>
    <link href="/css/prism.css" rel="stylesheet" id="style" />
    @*<link href="~/css/prism.css" rel="stylesheet" id="style" type="text/css"/>*@
    <script src="https://cdnjs.cloudflare.com/ajax/libs/prism/9000.0.1/components/prism-csharp.js"></script>


</head>
<body>
    <div class="container-fluid p-0">
        <div class="hamburger-menu">
        <header>
            <nav class="navbar navbar-expand-md navbar-toggleable-md border-bottom box-shadow navStyling">
                <div class="container-fluid">
                    <a class="navbar-brand nav-text-header nav-text-styling" asp-area="" asp-controller="Home" asp-action="Index"><img class="logotype" src="/images/code-cave-logo.png" /></a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"> <i class="bi bi-list size-burger"></i></span>
                    </button>
                    <div class="navbar-collapse collapse d-md-inline-flex justify-content-center">
                        <ul class="navbar-nav flex-grow-1">
                            
                            <li class="nav-item">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    <a class="nav-link nav-text nav-text-styling" asp-area="" asp-controller="Admin" asp-action="LogOut">Sign out</a>

                                }
                                else
                                {

                                    <a class="nav-link nav-text nav-text-styling" asp-area="" asp-controller="Admin" asp-action="LogIn">Admin</a>
                                }
                              
                                @(await Component.InvokeAsync("MenuList"))
                               
                            </li>
                        </ul>
                    </div>

                    

                </div>
            </nav>
        </header>
        </div>
        <div class="row">

            <div class="col-0 col-md-3 sticky-top listLayout">
                <div class="responsive-menu">
                    <a class="navbar-brand nav-text-header nav-text-styling" asp-area="" asp-controller="Home" asp-action="Index"><img class="logotype" src="/images/code-cave-logo.png" /></a>
                    <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        @if (User.Identity.IsAuthenticated)
                        {
                            <a class="nav-link nav-text nav-text-styling" asp-area="" asp-controller="Admin" asp-action="LogOut">Sign out</a>

                        }
                        else
                        {

                            <a class="nav-link nav-text nav-text-styling" asp-area="" asp-controller="Admin" asp-action="LogIn">Admin</a>
                        }
                     
                    </li>
                    </ul>
                    <div class="d-flex flex-column align-items-left sticky-top min-vh-100 border-end border-2 pt-sm-3">
                        @(await Component.InvokeAsync("MenuList"))
                    </div>
                </div>
            </div>
            <div class="col-12 col-md-9 p-3 min-vh-100">
                <div class="container">
                    <main role="main" class="pb-3">
                        @RenderBody()
                    </main>
                </div>
            </div>
        </div>
    </div>


    <footer class="border-top footer text-muted">
        <div class="container">
            The Code Cave  - &copy; 2023 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    <script>
        tinymce.init({
            selector: 'textarea#codesample',
            height: 500,
            plugins: 'codesample code lists',

            codesample_languages: [
                { text: 'HTML/XML', value: 'markup' },
                { text: 'JavaScript', value: 'javascript' },
                { text: 'CSS', value: 'css' },
                { text: 'PHP', value: 'php' },
                { text: 'Ruby', value: 'ruby' },
                { text: 'Python', value: 'python' },
                { text: 'Java', value: 'java' },
                { text: 'C', value: 'c' },
                { text: 'C#', value: 'csharp' },
                { text: 'C++', value: 'cpp' }
            ],
            toolbar: 'codesample code numlist bullist',
            content_style: 'body { font-family:Raleway,Helvetica,Arial,sans-serif; font-size:16px }',
            content_css: '/site.css'

        });

        // Prevent Bootstrap dialog from blocking focusin
        document.addEventListener('focusin', (e) => {
            if (e.target.closest(".tox-tinymce, .tox-tinymce-aux, .moxman-window, .tam-assetmanager-root") !== null) {
                e.stopImmediatePropagation();
            }
        });
    </script>
    @*           <script id="full" type="text/html">

    function myFunction(x) {

    if (x.matches) { // If media query matches

    <div class="col - 3 sticky - top listLayout" >
    <div class="responsive-menu" >
    @(
    await Component.InvokeAsync("MenuList")
    )
    </div>
    </div>
    < div class="col-9 p-3 min-vh-100" >
    <div class="container" >
    <main role="main" class="pb-3" >
    @{RenderBody();}
    </main>
    </div>
    </div>;
    }
    else {
    <div class="container" >
    <main role="main" class="pb-3" >
    {@RenderBody();}
    </main>
    </div>;
    }
    }

    var x = window.matchMedia("(max-width: 768px)")
    myFunction(x) // Call listener function at run time
    x.addListener(myFunction) // Attach listener function on state changes

    </script>@**@
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>